import './src/fp/pipeline.js';
import './src/fp/compose.js';
import './src/fp/prepare.js';
import './src/fp/curry.js';
import './src/fp/detach.js';
import './src/fp/detachCurry.js';
import './src/fp/through.js';
import './src/fp/noop.js';
import './src/fp/if.js';
