
export default [
	'./SyncPromise.js',
	'./expressional-error-control.js',
	'./instanceof-types.js',
	'./lists-extend-array.js',
	'./promisive.js',
	'./global-constructors.js',
	'./async-function-prototype/limit.js',
	'./string-prototype/matchGroup.js',
	'./string-prototype/toXXXCase.js',
	'./string-prototype/find-index.js',
	'./array-prototype/forEach-fix.js',
	'./array-prototype/forEachAwait.js',
	'./array-prototype/mapAwait.js',
	'./array-prototype/flatMapAwait.js',
	'./array-prototype/get-and-subArray.js',
	'./array-prototype/set.js',
	'./array-prototype/finding.js',
];
